version: "3"

services:
    zen_web:
        image: miholeus/nginx:latest
        volumes:
            - .:/app
            - ./support/nginx/site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8082:80"
        links:
            - zen_php
        networks:
            - app_network
    zen_php:
        image: miholeus/php71:development
        tty: true
        volumes:
            - ./:/app
            - ./support/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        environment:
            - SYMFONY_ENV=dev
            - SYMFONY_DEBUG=1
            - SYMFONY__DATABASE__USER=${DB_USER}
            - SYMFONY__DATABASE__NAME=${DB_NAME}
            - SYMFONY__DATABASE__PASS=${DB_PASS}
            - SYMFONY__APP__SECRET=${APP_SECRET}
        working_dir: /app
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
        ipam:
            driver: default
            config:
            -
              subnet: 172.21.0.0/16