main:
    path: /
    controller: App\Controller\ShopController::main
flowers:
    path: /shop/flowers/{id}
    controller: App\Controller\ShopController::flowers
    requirements:
        id: '\d+'
    defaults:
        id: 1
order:
    path: /shop/order/{id}
    controller: App\Controller\ShopController::order
    requirements:
        id: '\d+'
contacts:
    path: /contacts
    controller: App\Controller\ShopController::contacts